### ISSUE TITLE
 Unknown compression method

### ISSUE THREAD

**Issue by cyrlhq** [ruda/rpm2cpio#1]
Hi, in PyCharm Terminal, I input "python rpm2cpio.py *.i586.rpm" and got "Error: *.i586.rpm Unknown compression method". The Python Version is 3.6, please tell me how to solve this problem, thank you!

**Comment by ruda** [comment]
At least one file from `*.586.rpm` is causing the `unknown compression method` issue. You must test them one by one to see who is causing the error and then provide me context to that rpm.

**Comment by cyrlhq** [comment]
> At least one file from `*.586.rpm` is causing the `unknown compression method` issue. You must test them one by one to see who is causing the error and then provide me context to that rpm.

Thanks for the reply. By stating "at least one file is causing the 'unknown compression method", do you mean the files in the CPIO archive or the METADATA header?

**Comment by ruda** [comment]
> Thanks for the reply. By stating "at least one file is causing the 'unknown compression method", do you mean the files in the CPIO archive or the METADATA header?

I mean one of the files that `'*.586.rpm` implies, my tool expect rpm files as arguments, I can't guess much about everything else.

**Comment by ruda** [comment]
Do you have the URL for the `*.586.rpm` packages?
